/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import java.util.Arrays;

import frontend.MainFrame;

public class App {
  
    public static void main(String[] args) {
       
        String sourceStr =  FileManager.upload("Prueba1.txt");
        Box [][] boxes =Convert.stringToBox2DArray(sourceStr);
        Box [][] copyBoxes =Convert.stringToBox2DArray(sourceStr);
        //Printer.show(boxes);
        Agent agent = new Agent("Goku");
        Environment environment = new Environment(boxes);
        String [] movements= {"right", "up", "left","down"};
        /*
        Search search = new Search(environment, agent);
        search.traverse();
        */
        BFS bfs =  new BFS(environment, agent, movements);
        bfs.traverse();
        //bfs.getPath(copyBoxes);
       
        new MainFrame();
        
        
    }
}
